events {}

http{
     server{
          listen 80;

          location / {
            proxy_pass http://backend:4000;
          }

          location /api {
          
               return 200 "200";
          }

          location /user{
               return 200 "user";
          }
     }
}