name: FastAPI CI Pipeline

on:
  push:
    branches: [ "main" ] # Chạy khi push lên nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build và Push Docker Image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tạo tag dựa trên mã commit để dễ quản lý
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:${{ github.sha }}